version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o backend/bin/go-rest-api main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go

  proto.gen:
    desc: Generate protos
    cmds:
      - protoc -I=backend/pkg/proto --go_out ./backend/gen --go_opt=paths=source_relative --go-grpc_out ./backend/gen --go-grpc_opt=paths=source_relative --grpc-gateway_out ./backend/gen --grpc-gateway_opt=paths=source_relative backend/pkg/proto/interview.proto