version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/hashishaw/hc-intern/backend/internal github.com/hashishaw/hc-intern/backend/pkg/swagger

  swagger.validate:
    desc: Validate swagger
    cmds:
      - swagger validate pkg/swagger/swagger.yml

  swagger.doc:
    desc: Doc for swagger
    cmds:
      - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html

  proto.gen:
    desc: Generate protos
    cmds:
      - protoc -I=pkg/proto --go_out ./gen --go_opt=paths=source_relative --go-grpc_out ./gen --go-grpc_opt=paths=source_relative --grpc-gateway_out ./gen --grpc-gateway_opt=paths=source_relative pkg/proto/interview.proto