// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAPIInterviewIDOKCode is the HTTP code returned for type GetAPIInterviewIDOK
const GetAPIInterviewIDOKCode int = 200

/*GetAPIInterviewIDOK Returns interview found.

swagger:response getApiInterviewIdOK
*/
type GetAPIInterviewIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetAPIInterviewIDOK creates GetAPIInterviewIDOK with default headers values
func NewGetAPIInterviewIDOK() *GetAPIInterviewIDOK {

	return &GetAPIInterviewIDOK{}
}

// WithPayload adds the payload to the get Api interview Id o k response
func (o *GetAPIInterviewIDOK) WithPayload(payload string) *GetAPIInterviewIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api interview Id o k response
func (o *GetAPIInterviewIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInterviewIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAPIInterviewIDNotFoundCode is the HTTP code returned for type GetAPIInterviewIDNotFound
const GetAPIInterviewIDNotFoundCode int = 404

/*GetAPIInterviewIDNotFound Returns interview not found.

swagger:response getApiInterviewIdNotFound
*/
type GetAPIInterviewIDNotFound struct {
}

// NewGetAPIInterviewIDNotFound creates GetAPIInterviewIDNotFound with default headers values
func NewGetAPIInterviewIDNotFound() *GetAPIInterviewIDNotFound {

	return &GetAPIInterviewIDNotFound{}
}

// WriteResponse to the client
func (o *GetAPIInterviewIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
