// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAPIInterviewIDNoContentCode is the HTTP code returned for type GetAPIInterviewIDNoContent
const GetAPIInterviewIDNoContentCode int = 204

/*GetAPIInterviewIDNoContent Returns interview found.

swagger:response getApiInterviewIdNoContent
*/
type GetAPIInterviewIDNoContent struct {
}

// NewGetAPIInterviewIDNoContent creates GetAPIInterviewIDNoContent with default headers values
func NewGetAPIInterviewIDNoContent() *GetAPIInterviewIDNoContent {

	return &GetAPIInterviewIDNoContent{}
}

// WriteResponse to the client
func (o *GetAPIInterviewIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetAPIInterviewIDNotFoundCode is the HTTP code returned for type GetAPIInterviewIDNotFound
const GetAPIInterviewIDNotFoundCode int = 404

/*GetAPIInterviewIDNotFound Returns interview not found.

swagger:response getApiInterviewIdNotFound
*/
type GetAPIInterviewIDNotFound struct {
}

// NewGetAPIInterviewIDNotFound creates GetAPIInterviewIDNotFound with default headers values
func NewGetAPIInterviewIDNotFound() *GetAPIInterviewIDNotFound {

	return &GetAPIInterviewIDNotFound{}
}

// WriteResponse to the client
func (o *GetAPIInterviewIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
