// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIScheduleCandidateIDParams creates a new PostAPIScheduleCandidateIDParams object
// no default values defined in spec.
func NewPostAPIScheduleCandidateIDParams() PostAPIScheduleCandidateIDParams {

	return PostAPIScheduleCandidateIDParams{}
}

// PostAPIScheduleCandidateIDParams contains all the bound params for the post API schedule candidate ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAPIScheduleCandidateID
type PostAPIScheduleCandidateIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The id of the candidate.
	  Required: true
	  In: path
	*/
	CandidateID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAPIScheduleCandidateIDParams() beforehand.
func (o *PostAPIScheduleCandidateIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCandidateID, rhkCandidateID, _ := route.Params.GetOK("candidateId")
	if err := o.bindCandidateID(rCandidateID, rhkCandidateID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCandidateID binds and validates parameter CandidateID from path.
func (o *PostAPIScheduleCandidateIDParams) bindCandidateID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CandidateID = raw

	return nil
}
