// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAPIScheduleCandidateIDOKCode is the HTTP code returned for type PostAPIScheduleCandidateIDOK
const PostAPIScheduleCandidateIDOKCode int = 200

/*PostAPIScheduleCandidateIDOK Returns the interview id for that candidate.

swagger:response postApiScheduleCandidateIdOK
*/
type PostAPIScheduleCandidateIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostAPIScheduleCandidateIDOK creates PostAPIScheduleCandidateIDOK with default headers values
func NewPostAPIScheduleCandidateIDOK() *PostAPIScheduleCandidateIDOK {

	return &PostAPIScheduleCandidateIDOK{}
}

// WithPayload adds the payload to the post Api schedule candidate Id o k response
func (o *PostAPIScheduleCandidateIDOK) WithPayload(payload string) *PostAPIScheduleCandidateIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api schedule candidate Id o k response
func (o *PostAPIScheduleCandidateIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIScheduleCandidateIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
