consumes:
  - application/json
info:
  description: HTTP server in Go with Swagger endpoints definition.
  title: go-rest-api
  version: 0.1.0
produces:
  - application/json
schemes:
  - http
swagger: "2.0"

paths:
  /healthz:
    get:
      operationId: checkHealth
      produces:
        - text/plain
      responses:
        '200':
          description: OK message.
          schema:
            type: string
            enum:
              - OK

  /api/interview/{id}:
    get:
      description: Returns whether the id is valid.
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: The interview session id.
      responses:
        200:
          description: Returns interview found.
          schema:
            type: string
        404:
          description: Returns interview not found.

  /api/schedule/{candidateId}:
    post:
      description: Returns an interview id.
      produces:
        - application/json
      parameters:
        - name: candidateId
          in: path
          type: string
          required: true
          description: The id of the candidate.
      responses:
        200:
          description: Returns the interview id for that candidate.
          schema:
            type: string
